schema_version = "1.0.0"
id = "tool_starfield_animation_io"
version = "1.0.0"
name = "Starfield Animation"
tagline = "Import/Export Starfield Animation/Rig"
maintainer = "Deveris, Calaverah & Jojo"
type = "add-on"
blender_version_min = "4.3.0"
license = ["SPDX:MIT"]
